IGNITE-22403 CDC: Improve Kafka partition ranges assignment for appliers
apache/ignite-extensions pull request #272
Opened 2024-06-06 13:46 UTC by maksaska

Distribution for partitions from kafka topic over requested threads in `AbstractKafkaToIgniteCdcStreamer` (CDC Kafka to Ignite) is not uniform.

There might be cases with unequal load on threads, that reads data from kafka, which might result in overhead/bottleneck and slow workflow in general for the whole CDC with Kafka process. The improved version takes that into account. 

Initially, for uniform distribution to form, the streamer calculated the ratio between the number of partitions and the number of threads.It didn't take into account the modulus of the result, thus leading to underestimated number of partiotions one thread can take. The fixed version of the algorithm uses modulus to round up the underestimated number to pump up the load on the first threads. To make things work, the number of partitions taken by each thread is reevaulated for each thread, which allows to reduce the difference in parity and integral division in general. In other words, threads balance themself out while partitions are being distributed from the first thread to the last one.

2024-07-05 13:32 UTC, shishkovilja requested changes

2024-07-05 13:32 UTC, shishkovilja commented on modules/cdc-ext/src/main/java/org/apache/ignite/cdc/kafka/AbstractKafkaToIgniteCdcStreamer.java
> +    public static List<IgniteBiTuple<Integer, Integer>> getKafkaPartitionsDistribution(KafkaToIgniteCdcStreamerConfiguration streamerCfg) {
```suggestion
    public static List<IgniteBiTuple<Integer, Integer>> kafkaPartitions(KafkaToIgniteCdcStreamerConfiguration streamerCfg) {
```

2024-07-05 13:32 UTC, shishkovilja commented on modules/cdc-ext/src/main/java/org/apache/ignite/cdc/kafka/AbstractKafkaToIgniteCdcStreamer.java
> +        List<IgniteBiTuple<Integer, Integer>> distr = new ArrayList<>();
```suggestion
        List<IgniteBiTuple<Integer, Integer>> parts = new ArrayList<>();
```

2024-07-05 13:32 UTC, shishkovilja commented on modules/cdc-ext/src/main/java/org/apache/ignite/cdc/kafka/AbstractKafkaToIgniteCdcStreamer.java
> +        return distr;
```suggestion
        return parts;
```

2024-07-05 13:32 UTC, shishkovilja commented on modules/cdc-ext/src/main/java/org/apache/ignite/cdc/kafka/AbstractKafkaToIgniteCdcStreamer.java
> +        for (IgniteBiTuple<Integer, Integer> part : getKafkaPartitionsDistribution(streamerCfg)) {
```suggestion
        for (IgniteBiTuple<Integer, Integer> parts : kafkaPartitions(streamerCfg)) {
```

2024-07-05 13:32 UTC, shishkovilja commented on modules/cdc-ext/src/main/java/org/apache/ignite/cdc/kafka/AbstractKafkaToIgniteCdcStreamer.java
> +                part.get1(),
```suggestion
                parts.get1(), // kafkaPartFrom
```

2024-07-05 13:32 UTC, shishkovilja commented on modules/cdc-ext/src/main/java/org/apache/ignite/cdc/kafka/AbstractKafkaToIgniteCdcStreamer.java
> +                part.get2(),
```suggestion
                parts.get2(), // kafkaPartTo
```

2024-07-05 13:47 UTC, maksaska commented on modules/cdc-ext/src/main/java/org/apache/ignite/cdc/kafka/AbstractKafkaToIgniteCdcStreamer.java
> +    public static List<IgniteBiTuple<Integer, Integer>> getKafkaPartitionsDistribution(KafkaToIgniteCdcStreamerConfiguration streamerCfg) {
Done!

2024-07-05 13:47 UTC, maksaska commented on modules/cdc-ext/src/main/java/org/apache/ignite/cdc/kafka/AbstractKafkaToIgniteCdcStreamer.java
> +        return distr;
Renamed it

2024-07-05 13:48 UTC, maksaska commented on modules/cdc-ext/src/main/java/org/apache/ignite/cdc/kafka/AbstractKafkaToIgniteCdcStreamer.java
> +        for (IgniteBiTuple<Integer, Integer> part : getKafkaPartitionsDistribution(streamerCfg)) {
Done

2024-07-05 13:48 UTC, maksaska commented on modules/cdc-ext/src/main/java/org/apache/ignite/cdc/kafka/AbstractKafkaToIgniteCdcStreamer.java
> +        List<IgniteBiTuple<Integer, Integer>> distr = new ArrayList<>();
Done

2024-07-05 13:48 UTC, maksaska commented on modules/cdc-ext/src/main/java/org/apache/ignite/cdc/kafka/AbstractKafkaToIgniteCdcStreamer.java
> +                part.get2(),
Done

2024-07-08 13:23 UTC, shishkovilja approved these changes

2024-07-08 13:24 UTC, shishkovilja requested changes
Please, fix my comments

2024-07-08 13:41 UTC, maksaska commented on modules/cdc-ext/src/main/java/org/apache/ignite/cdc/kafka/AbstractKafkaToIgniteCdcStreamer.java
> +        int counter = 0;
Renamed the variable accroding to the rules

2024-07-08 13:41 UTC, maksaska commented on modules/cdc-ext/src/main/java/org/apache/ignite/cdc/kafka/AbstractKafkaToIgniteCdcStreamer.java
> +            addAndStart("applier-thread-" + counter++, applier);
Renamed the variable accroding to the rules

2024-07-08 13:41 UTC, maksaska commented on modules/cdc-ext/src/test/java/org/apache/ignite/cdc/kafka/KafkaToIgnitePartitionDistributionTest.java
> +    private void testKafkaPartitionsCase(int threadCnt, int partFrom, int partTo, List<IgniteBiTuple<Integer, Integer>> result) {
Renamed the variable accroding to the rules

2024-07-08 13:42 UTC, maksaska commented on modules/cdc-ext/src/test/java/org/apache/ignite/cdc/kafka/KafkaToIgnitePartitionDistributionTest.java
> +     * Checks the topic partitions distribution over specified number of threads for specified parameters.
Done!

2024-07-08 13:42 UTC, maksaska commented on modules/cdc-ext/src/test/java/org/apache/ignite/cdc/kafka/KafkaToIgnitePartitionDistributionTest.java
> +    /** Checks the topic partitions distribution over specified number of threads. */
Done!

2024-07-08 13:42 UTC, maksaska commented on modules/cdc-ext/src/test/java/org/apache/ignite/cdc/kafka/KafkaToIgnitePartitionDistributionTest.java
> +/** Tests the kafka topic partitions distribution over specified number of threads. */
Changed the javadoc message

2024-07-08 13:42 UTC, maksaska commented on modules/cdc-ext/src/test/java/org/apache/ignite/cdc/kafka/KafkaToIgnitePartitionDistributionTest.java
> +     * @param threadCnt Thread count.
Done!

2024-07-08 13:42 UTC, maksaska commented on modules/cdc-ext/src/test/java/org/apache/ignite/cdc/kafka/KafkaToIgnitePartitionDistributionTest.java
> +     * @param result List of pairs defining partition ranges for each applier thread.
Done!

2024-07-08 13:42 UTC, maksaska commented on modules/cdc-ext/src/test/java/org/apache/ignite/cdc/kafka/KafkaToIgnitePartitionDistributionTest.java
> +        assertEquals(result, kafkaPartitions(streamerCfg));
Done!

2024-07-09 09:06 UTC, shishkovilja approved these changes

2024-07-10 14:55 UTC, NSAmelchev approved these changes

2024-07-10 14:57 UTC, merged