IGNITE-19528 CDC examples with cdc-start-up.sh
apache/ignite-extensions pull request #285
Opened 2024-08-26 11:21 UTC by maksaska

Currently, there are no examples for different CDC configurations and corresponding documentation. We need step-by-step documentation for active-passive, active-active cases and for different clients and transports (Ignite2Ignite, Ignite through Kafka).

What is new: 
* Configuration examples for different replication regimes and data transport
* cdc-start-up.sh to start examples
    * Ignite instance start-up
    * CDC clisnt instance start-up
    * Active-Passive/Active-Active replication 
    * CDC check

2025-02-06 15:25 UTC, timoninmaxim commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +		* --ignite-to-ignite			Creates a single server client (Thick client), `
just "thick client", server client sounds weird :)

2025-02-06 15:26 UTC, timoninmaxim commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +                                      `An ignite instance will be started with basic CDC configuration.
add path to ignite configuration.

2025-02-06 15:31 UTC, timoninmaxim commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +		* --ignite-to-kafka		Creates a cdc client, used to transfer data from source-cluster to specified Kafka topic.
What is cdc client? It must be one of thin or thick?

2025-02-06 15:33 UTC, timoninmaxim commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +# Checks --cdc-client arguments
No such parameter

2025-02-06 15:36 UTC, timoninmaxim commented on modules/cdc-ext/examples/config/cdc-start-up/cdc-base-configuration.xml
> +			<bean class="org.apache.ignite.spi.discovery.tcp.ipfinder.vm.TcpDiscoveryVmIpFinder">
Fix indentions in configs also

2025-02-06 15:39 UTC, timoninmaxim commented on modules/cdc-ext/README.txt
> +ignite-cdc-ext.zip
No such file, ignite-cdc-ext-bin.zip?

2025-02-06 16:13 UTC, maksaska commented on modules/cdc-ext/README.txt
> +Now, you have additional binary `$IGNITE_HOME/bin/kafka-to-ignite.sh` and `$IGNITE_HOME/libs/optional/ignite-cdc-ext` module.
Added examples in README

2025-02-06 16:13 UTC, maksaska commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +		* --ignite-to-ignite			Creates a single server client (Thick client), `
Yeah) 
Fixed it

2025-02-06 16:14 UTC, maksaska commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +                                      `An ignite instance will be started with basic CDC configuration.
Added the path

2025-02-06 16:15 UTC, maksaska commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +		* --ignite-to-kafka		Creates a cdc client, used to transfer data from source-cluster to specified Kafka topic.
It's neither of both. Renamed it to cdc consumer

2025-02-06 16:15 UTC, maksaska commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +# Checks --cdc-client arguments
fixed it

2025-02-06 16:15 UTC, maksaska commented on modules/cdc-ext/README.txt
> +ignite-cdc-ext.zip
fixed

2025-02-06 17:54 UTC, timoninmaxim requested changes

2025-02-06 17:54 UTC, timoninmaxim commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +		* thick				Creates a single server client (Thick client), `
just thick client

2025-02-06 17:54 UTC, timoninmaxim commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +		* --ignite-to-kafka		Creates a cdc consumer, used to transfer data from source-cluster to specified Kafka topic.
thick client?

2025-02-06 17:54 UTC, timoninmaxim commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +		* --cluster clusterNum		Optional parameter for the cluster number (1 or 2) that initially stores the entry.
default value?

2025-02-06 17:54 UTC, timoninmaxim commented on modules/cdc-ext/README.txt
> +This module provides the clients with a simple CDC implementations strategies for inter-cluster communication. Active-Passive and Active-Active replication regimes can be established with different C
with a simple CDC implementations -> with simple CDC implementations

2025-02-06 17:54 UTC, timoninmaxim commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +-c, --cdc-consumer consumerMode ignitePropertiesPath `
why `--ignite` goes with "igniteProperties" but `--cdc-consumer` and `--kafka-to-ignite` with "ignitePropertiesPath"?

2025-02-06 17:54 UTC, timoninmaxim commented on modules/cdc-ext/README.txt
> +==== Installation
Let's rename file to "README.md" to show the formatting

2025-02-06 17:54 UTC, timoninmaxim commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +  checkMissing "${script_param-}" "ignitePropertiesPath" "${2-}"
Why "igniteProperties**Path**" why parameter name is "igniteProperties"

2025-02-06 17:54 UTC, timoninmaxim commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +	infoMsg "Starting CDC client for ${ignite_properties_path-} with ${consumer_mode-}"
CDC consumer?

2025-02-06 17:54 UTC, timoninmaxim commented on modules/cdc-ext/examples/config/cdc-start-up/cdc-base-configuration.xml
> +        <property name="conflictResolveField" value="val2"/>
Do we need this setting?

2025-02-06 17:54 UTC, timoninmaxim commented on modules/cdc-ext/examples/config/cdc-start-up/cdc-base-configuration.xml
> +        <property name="conflictResolveField" value="val2"/>
I suppose we need an example that shows this field in action

2025-02-06 18:32 UTC, maksaska commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +		* thick				Creates a single server client (Thick client), `
done

2025-02-06 18:32 UTC, maksaska commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +		* --cluster clusterNum		Optional parameter for the cluster number (1 or 2) that initially stores the entry.
added default

2025-02-06 18:32 UTC, maksaska commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +		* --ignite-to-kafka		Creates a cdc consumer, used to transfer data from source-cluster to specified Kafka topic.
fixed

2025-02-06 18:32 UTC, maksaska commented on modules/cdc-ext/README.txt
> +This module provides the clients with a simple CDC implementations strategies for inter-cluster communication. Active-Passive and Active-Active replication regimes can be established with different C
fixed the typo

2025-02-06 18:33 UTC, maksaska commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +-c, --cdc-consumer consumerMode ignitePropertiesPath `
fixed

2025-02-06 18:34 UTC, maksaska commented on modules/cdc-ext/README.txt
> +==== Installation
Done

2025-02-06 18:34 UTC, maksaska commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +  checkMissing "${script_param-}" "ignitePropertiesPath" "${2-}"
Typo. Fixed it

2025-02-06 18:34 UTC, maksaska commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +	infoMsg "Starting CDC client for ${ignite_properties_path-} with ${consumer_mode-}"
Fixed it

2025-02-17 17:10 UTC, maksaska commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +		* --ignite-to-kafka		Creates a cdc consumer, used to transfer data from source-cluster to specified Kafka topic.
fixed

2025-02-17 17:11 UTC, maksaska commented on modules/cdc-ext/examples/config/cdc-start-up/cdc-base-configuration.xml
> +        <property name="conflictResolveField" value="val2"/>
Yeah. In the script we use it ass version field of value JSON, that is pushed to the source cluster

2025-03-11 10:22 UTC, timoninmaxim requested changes

2025-03-11 10:22 UTC, timoninmaxim commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +-c, --ignite-cdc consumerMode igniteProperties `
igniteProperties desc is missing

2025-03-11 10:22 UTC, timoninmaxim commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +--check-cdc --key intNum1 --value intNum2 [--cluster clusterNum] `
intNum2 is bad name as it expect json.

2025-03-11 10:22 UTC, timoninmaxim commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +	value=$(echo $jsonValue | awk -F'"intVal": ' '{ print $2 }' | awk -F',' '{ print $1 }')
Do we really need check anything except "version" field?

2025-03-14 19:15 UTC, maksaska commented on modules/cdc-ext/README.md
> +This module provides the clients with simple CDC implementations strategies for inter-cluster communication. Active-Passive and Active-Active replication regimes can be established with different CDC
fixed

2025-03-14 19:15 UTC, maksaska commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +-c, --ignite-cdc consumerMode igniteProperties `
Updated description

2025-03-14 19:15 UTC, maksaska commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +--check-cdc --key intNum1 --value intNum2 [--cluster clusterNum] `
Yep. Changed it

2025-03-21 19:34 UTC, maksaska commented on modules/cdc-ext/examples/cdc-start-up/cdc-start-up.sh
> +	value=$(echo $jsonValue | awk -F'"intVal": ' '{ print $2 }' | awk -F',' '{ print $1 }')
Actually we don't have to do it anymore/ Without the check we will be able to see what happens if no conflictResloverField is specified in the entry

2025-03-27 15:50 UTC, merged